package com.regu.orchestration.dto;

import java.util.List;

/**
 * The final structured compliance report returned to the caller.
 *
 * <p>Produced by {@code ReportGenerationService} after aggregating Stage 1
 * classification, Stage 2 gap analysis (if applicable), and LLM-generated prose.
 *
 * @param summary           2–3 paragraph executive summary
 * @param classification    the Stage 1 risk classification result
 * @param gapAnalyses       Annex IV gap results (empty list if not high-risk)
 * @param sections          ordered report sections with citations
 * @param citations         all resolved citations used in the report
 * @param disclaimer        standard legal disclaimer text
 * @param generatedAt       ISO-8601 timestamp of generation
 * @param modelUsed         LLM model identifier
 * @param totalProcessingMs wall-clock time for the full generation pipeline
 */
public record ComplianceReport(
        String summary,
        ClassificationResult classification,
        List<GapAnalysisResult> gapAnalyses,
        List<ReportSection> sections,
        List<CitationEntry> citations,
        String disclaimer,
        String generatedAt,
        String modelUsed,
        long totalProcessingMs
) {
    public static final String STANDARD_DISCLAIMER =
            "This report is generated by REGU, an AI-powered compliance tool. " +
            "It is not legal advice. For definitive compliance determinations, " +
            "consult a qualified legal professional.";
}
