-- V9: Extend legal_chunks with extraction-phase structural metadata.
--
-- Adds the columns produced by the EU AI Act corpus extraction scripts:
--   chunk_type        — more granular than document_type (e.g. article_paragraph,
--                       annex_point, recital_text, definition_entry)
--   source_chunk_id   — stable string ID used for idempotent ingestion
--                       (e.g. eu_ai_act_recital_001, eu_ai_act_art10_para2)
--   recital_number    — recital sequence number (NULL for non-recital chunks)
--   annex_section     — named section within an annex (e.g. "Section A")
--   chapter_number    — chapter number (NULL for recitals / top-level articles)
--   chapter_title     — chapter title (NULL for recitals / top-level articles)
--   section_number    — numbered section within a chapter (NULL if not applicable)
--   section_title     — section title (NULL if not applicable)
--   citation_eligible — whether this chunk is eligible for inline citation in reports
--
-- Also adds three supporting indexes.

-- New structural columns
ALTER TABLE legal_chunks
    ADD COLUMN chunk_type        VARCHAR(50),
    ADD COLUMN source_chunk_id   VARCHAR(200),
    ADD COLUMN recital_number    INTEGER,
    ADD COLUMN annex_section     VARCHAR(200),
    ADD COLUMN chapter_number    INTEGER,
    ADD COLUMN chapter_title     VARCHAR(500),
    ADD COLUMN section_number    INTEGER,
    ADD COLUMN section_title     VARCHAR(500),
    ADD COLUMN citation_eligible BOOLEAN NOT NULL DEFAULT TRUE;

-- Unique constraint for idempotent ingestion
ALTER TABLE legal_chunks
    ADD CONSTRAINT uq_legal_chunks_source_chunk_id UNIQUE (source_chunk_id);

-- Indexes for retrieval filters used in Phase 4
CREATE INDEX idx_legal_chunks_chunk_type      ON legal_chunks (chunk_type)
    WHERE chunk_type IS NOT NULL;

CREATE INDEX idx_legal_chunks_recital         ON legal_chunks (recital_number)
    WHERE recital_number IS NOT NULL;

CREATE INDEX idx_legal_chunks_chapter         ON legal_chunks (chapter_number)
    WHERE chapter_number IS NOT NULL;

-- Comments
COMMENT ON COLUMN legal_chunks.chunk_type        IS 'Granular chunk type: article_paragraph, annex_point, recital_text, definition_entry';
COMMENT ON COLUMN legal_chunks.source_chunk_id   IS 'Stable string ID for idempotent re-ingestion (generated by extraction script)';
COMMENT ON COLUMN legal_chunks.recital_number    IS 'Recital sequence number; NULL for non-recital chunks';
COMMENT ON COLUMN legal_chunks.annex_section     IS 'Named section within an annex (e.g. "Section A — Biometric systems")';
COMMENT ON COLUMN legal_chunks.chapter_number    IS 'Chapter number; NULL for recitals and standalone top-level articles';
COMMENT ON COLUMN legal_chunks.chapter_title     IS 'Chapter title (e.g. "Requirements for high-risk AI systems")';
COMMENT ON COLUMN legal_chunks.section_number    IS 'Numbered section within a chapter; NULL if not applicable';
COMMENT ON COLUMN legal_chunks.section_title     IS 'Section title; NULL if not applicable';
COMMENT ON COLUMN legal_chunks.citation_eligible IS 'True if this chunk may appear as an inline citation in compliance reports';
